### PR TITLE
[18.0][MIG] server_environment_ir_config_parameter: Migration to 18.0

### PR DESCRIPTION
**Pull request by chaule97**

### CODE REVIEW

**Comment by dzungtran89** [comment]
@chaule97 could you please seperate the pre-commit auto fixes commit and migration commit?

**Comment by dzungtran89** [comment]
Minor changes requested, lgtm overall.

**Comment by chaule97** [comment]
> @chaule97 could you please seperate the pre-commit auto fixes commit and migration commit?

Hi @dzungtran89 , I have reset and tried to pre-commit again but there is no change

**Comment by dzungtran89** [comment]
> > @chaule97 could you please seperate the pre-commit auto fixes commit and migration commit?
> 
> Hi @dzungtran89 , I have reset and tried to pre-commit again but there is no change

You can check to this [PR](https://github.com/trisdoan/social/pull/19) for reference.

**Comment by chaule97** [comment]
Hi anh @dzungtran89, I can pre-commit and have pushed again

**Review by dzungtran89 — APPROVED** [review]

**Pull request closed without merging**
